name: neuro_companion
description: A lightweight mental wellness assistant.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  path_provider: ^2.1.2
  share_plus: ^7.0.0
  speech_to_text: ^6.3.0
  flutter_riverpod: ^2.4.0
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.3.3
  azure_storage_blobs: ^0.11.0
  azure_identity: ^0.1.0
  file_picker: ^6.1.1
  shimmer: ^3.0.0
  connectivity_plus: ^4.0.2
  integration_test:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
