name: on_the_go_logging
description: "Wearable integration: on the go logging"
version: 0.1.0
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^5.0.0
  flutter_tts: ^3.5.0
